# Generated by Django 2.2.2 on 2019-09-25 05:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='donatemoney',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tid', models.IntegerField()),
                ('user_name', models.CharField(max_length=150, null=True)),
                ('transfer', models.CharField(default=0, max_length=264)),
                ('amount', models.IntegerField(default=0)),
                ('orphanage', models.CharField(max_length=264)),
                ('description', models.CharField(default=None, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='donatevaluables',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tid', models.IntegerField()),
                ('user_name', models.CharField(max_length=150)),
                ('donation_type', models.CharField(choices=[('F', 'Food'), ('C', 'Clothes'), ('B', 'Book'), ('E', 'Eletrical Appliances'), ('O', 'other')], max_length=1)),
                ('date_of_donation', models.DateTimeField(default=django.utils.timezone.now)),
                ('weight', models.IntegerField()),
                ('length', models.IntegerField()),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('description', models.CharField(default=None, max_length=100)),
                ('status', models.IntegerField()),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
