# Generated by Django 2.2.6 on 2019-10-27 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donatemoney',
            name='id',
        ),
        migrations.AlterField(
            model_name='donatemoney',
            name='tid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
