# Generated by Django 2.2.6 on 2019-11-04 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0002_auto_20191027_1252'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donatemoney',
            options={'get_latest_by': ['tid']},
        ),
        migrations.AlterModelOptions(
            name='donatevaluables',
            options={'get_latest_by': ['tid']},
        ),
        migrations.RemoveField(
            model_name='donatevaluables',
            name='date_of_donation',
        ),
        migrations.RemoveField(
            model_name='donatevaluables',
            name='id',
        ),
        migrations.RemoveField(
            model_name='donatevaluables',
            name='user_id',
        ),
        migrations.AddField(
            model_name='donatevaluables',
            name='breadth',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='donatemoney',
            name='user_name',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='donatevaluables',
            name='tid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='donatevaluables',
            name='user_name',
            field=models.CharField(max_length=15),
        ),
    ]
