# Generated by Django 2.2.6 on 2019-11-04 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0003_auto_20191104_1854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donatevaluables',
            name='width',
        ),
    ]
