# Generated by Django 2.1.2 on 2019-10-12 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orphanage',
            name='phone_no',
            field=models.IntegerField(null=True),
        ),
    ]
