# Generated by Django 2.2.5 on 2019-11-14 16:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='date_of_event',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='events',
            name='date_of_post',
            field=models.DateField(default=datetime.date(2019, 11, 14)),
        ),
        migrations.AlterField(
            model_name='events',
            name='status',
            field=models.CharField(max_length=50),
        ),
    ]
