# Generated by Django 2.1.2 on 2019-10-12 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_auto_20191012_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='orphanage',
            name='lat',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='orphanage',
            name='lon',
            field=models.FloatField(null=True),
        ),
    ]
