# Generated by Django 2.1.2 on 2019-12-11 16:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_auto_20191211_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verification',
            name='hit',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 11, 21, 53, 16, 182770)),
        ),
    ]
