# Generated by Django 2.2.6 on 2019-11-10 10:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('homepage', '0003_auto_20191012_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='orphanage',
            name='orphanage_id',
            field=models.ForeignKey(default='5', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='addorphan',
            name='orphanage_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='homepage.Orphanage'),
        ),
        migrations.AlterField(
            model_name='addorphan',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='donation',
            name='orphanage_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.Orphanage'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='emergency',
            name='orphanage_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.Orphanage'),
        ),
        migrations.AlterField(
            model_name='moneydonation',
            name='orphanage_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='homepage.Orphanage'),
        ),
        migrations.AlterField(
            model_name='moneydonation',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='orphan',
            name='orphanage_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.Orphanage'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='danation_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.Donation'),
        ),
        migrations.AlterField(
            model_name='type',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='donatevaluables',
            fields=[
                ('tid', models.AutoField(primary_key=True, serialize=False)),
                ('donation_type', models.CharField(choices=[('F', 'Food'), ('C', 'Clothes'), ('B', 'Book'), ('E', 'Eletrical Appliances'), ('O', 'other')], max_length=1)),
                ('date_of_donation', models.DateTimeField(default=django.utils.timezone.now)),
                ('quantity', models.IntegerField()),
                ('description', models.CharField(default=None, max_length=100)),
                ('status', models.IntegerField()),
                ('orphanage_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='homepage.Donation')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'get_latest_by': ['tid'],
            },
        ),
        migrations.CreateModel(
            name='donatemoney',
            fields=[
                ('tid', models.AutoField(primary_key=True, serialize=False)),
                ('transfer', models.CharField(default=0, max_length=264)),
                ('amount', models.IntegerField(default=0)),
                ('description', models.CharField(default=None, max_length=50)),
                ('orphanage_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='homepage.Donation')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'get_latest_by': ['tid'],
            },
        ),
    ]
