# Generated by Django 2.1.7 on 2019-11-09 15:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('homepage', '0003_auto_20191031_1906'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_event', models.DateTimeField()),
                ('date_of_post', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.IntegerField()),
                ('description', models.CharField(max_length=200)),
                ('event', models.CharField(max_length=30)),
                ('orphanage_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='homepage.Orphanage')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
