# Generated by Django 2.2.5 on 2019-12-10 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_review_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orphanage',
            name='phone_no',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='phone_no',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
