# Generated by Django 2.2.6 on 2019-11-15 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_auto_20191115_0016'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donatemoney',
            options={'get_latest_by': ['tid', 'status']},
        ),
        migrations.AlterModelOptions(
            name='donatevaluables',
            options={'get_latest_by': ['tid', 'status']},
        ),
        migrations.AddField(
            model_name='donatevaluables',
            name='address',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='donatevaluables',
            name='object_name',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='donatevaluables',
            name='orphanage_name',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
