# Generated by Django 2.2.6 on 2019-11-10 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_auto_20191110_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='donatemoney',
            name='status',
            field=models.IntegerField(default='0'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='donatemoney',
            name='orphanage_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='homepage.Orphanage'),
        ),
        migrations.AlterField(
            model_name='donatevaluables',
            name='orphanage_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='homepage.Orphanage'),
        ),
    ]
