# Generated by Django 2.1.7 on 2019-11-09 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_events'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orphan',
            name='orphanage_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.Orphanage'),
        ),
    ]
