# Generated by Django 2.1.2 on 2019-11-15 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_auto_20191115_0016'),
    ]

    operations = [
        migrations.CreateModel(
            name='verification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyname', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('token', models.CharField(max_length=40)),
            ],
        ),
    ]
