# Generated by Django 2.2.5 on 2019-12-10 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_auto_20191210_1250'),
    ]

    operations = [
        migrations.CreateModel(
            name='catering',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.IntegerField()),
                ('company_name', models.CharField(max_length=50)),
                ('items', models.CharField(default=None, max_length=500)),
                ('price', models.CharField(default=None, max_length=500)),
                ('status', models.CharField(default='Not Accepted', max_length=20)),
                ('image', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
