# Generated by Django 2.1.7 on 2019-11-09 17:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_auto_20191109_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orphan',
            name='date_of_birth',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
