# Generated by Django 2.2.6 on 2019-11-16 04:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_verification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='date_of_post',
            field=models.DateField(default=datetime.date(2019, 11, 16)),
        ),
    ]
