# Generated by Django 2.2.6 on 2019-11-10 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_auto_20191110_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='orphanage',
            name='account',
            field=models.CharField(default='harshab@harsha.com', max_length=300),
            preserve_default=False,
        ),
    ]
