# Generated by Django 2.2.5 on 2019-12-10 12:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_verification_hit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verification',
            name='hit',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 10, 17, 51, 42, 916920)),
        ),
    ]
