# Generated by Django 2.1.7 on 2019-11-09 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_auto_20191109_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='date_of_event',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='orphan',
            name='date_of_birth',
            field=models.DateField(),
        ),
    ]
