# Generated by Django 2.2.6 on 2019-11-13 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_orphanage_account'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donatemoney',
            options={'get_latest_by': ['tid', 'status']},
        ),
        migrations.AlterModelOptions(
            name='donatevaluables',
            options={'get_latest_by': ['tid', 'status']},
        ),
    ]
