# Generated by Django 2.2.6 on 2019-11-16 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_auto_20191116_1010'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donatemoney',
            options={'get_latest_by': ['tid', 'status']},
        ),
        migrations.AlterModelOptions(
            name='donatevaluables',
            options={'get_latest_by': ['tid', 'status']},
        ),
        migrations.AddField(
            model_name='donatemoney',
            name='orphanage_name',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='donatevaluables',
            name='address',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='donatevaluables',
            name='object_name',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='donatevaluables',
            name='orphanage_name',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
