# Generated by Django 2.2.5 on 2019-12-10 14:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0007_auto_20191210_1751'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cateringcompany',
            old_name='user_id',
            new_name='company_id',
        ),
        migrations.AlterField(
            model_name='verification',
            name='hit',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 10, 20, 14, 18, 748511)),
        ),
    ]
