# Generated by Django 2.2.6 on 2019-11-14 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0007_auto_20191113_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='donatevaluables',
            name='address',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
