# Generated by Django 2.2.6 on 2019-11-15 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0008_donatevaluables_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='donatevaluables',
            name='object_name',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='donatevaluables',
            name='orphanage_name',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
