# Generated by Django 2.2.6 on 2019-11-16 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0008_auto_20191116_1324'),
    ]

    operations = [
        migrations.CreateModel(
            name='test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gey', models.CharField(max_length=20)),
                ('will', models.CharField(max_length=20)),
            ],
        ),
    ]
