# Generated by Django 2.2.6 on 2019-11-16 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0009_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='test',
            name='pro',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='homepage.program'),
            preserve_default=False,
        ),
    ]
