# Generated by Django 2.2.6 on 2019-12-11 22:14

import datetime
from django.db import migrations, models
import homepage.models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0013_auto_20191211_2326'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=homepage.models.user_image_upload_url),
        ),
        migrations.AlterField(
            model_name='events',
            name='date_of_post',
            field=models.DateField(default=datetime.date(2019, 12, 12)),
        ),
        migrations.AlterField(
            model_name='verification',
            name='hit',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 12, 3, 44, 18, 680324)),
        ),
    ]
