# Generated by Django 2.2.5 on 2019-12-10 05:33

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import homepage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CateringCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=300)),
                ('image', models.ImageField(blank=True, null=True, upload_to=homepage.models.company_image_upload_url)),
            ],
        ),
        migrations.CreateModel(
            name='Orphanage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orphanage_name', models.CharField(max_length=30)),
                ('year_of_establishment', models.IntegerField()),
                ('lon', models.FloatField(null=True)),
                ('lat', models.FloatField(null=True)),
                ('address', models.CharField(max_length=50)),
                ('phone_no', models.IntegerField(null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=homepage.models.orphanage_image_upload_url)),
                ('description', models.CharField(max_length=300)),
                ('account', models.CharField(default=None, max_length=300, null=True)),
                ('status', models.CharField(default='Freshly Applied', max_length=50)),
                ('orphanage_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('danation_id', models.IntegerField()),
                ('company_name', models.CharField(max_length=50)),
                ('cost', models.IntegerField()),
                ('type', models.CharField(max_length=20)),
                ('duration', models.CharField(max_length=20)),
                ('status', models.CharField(default='Not Accepted', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='verification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=40)),
                ('companyname', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='homepage.CateringCompany')),
                ('user_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('phone_no', models.IntegerField(null=True)),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_no', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='success',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='Freshly Applied', max_length=30)),
                ('orphanage_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='homepage.Orphanage')),
            ],
        ),
        migrations.CreateModel(
            name='review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=150, null=True)),
                ('rating', models.IntegerField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Orphan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orphan_name', models.CharField(max_length=30)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('special_skills', models.CharField(max_length=50)),
                ('orphanage_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.Orphanage')),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_event', models.DateField()),
                ('date_of_post', models.DateField(default=datetime.date(2019, 12, 10))),
                ('status', models.CharField(default='Freshly Applied', max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('event', models.CharField(max_length=30)),
                ('orphanage_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='homepage.Orphanage')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Emergency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirement', models.CharField(max_length=100)),
                ('situation', models.CharField(max_length=500)),
                ('date_of_post', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.IntegerField()),
                ('orphanage_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.Orphanage')),
            ],
        ),
        migrations.CreateModel(
            name='donatevaluables',
            fields=[
                ('tid', models.AutoField(primary_key=True, serialize=False)),
                ('donation_type', models.CharField(choices=[('F', 'Food'), ('C', 'Clothes'), ('B', 'Book'), ('E', 'Eletrical Appliances'), ('O', 'other')], max_length=1)),
                ('orphanage_name', models.CharField(default=None, max_length=100)),
                ('date_of_donation', models.DateTimeField(default=django.utils.timezone.now)),
                ('quantity', models.IntegerField()),
                ('object_name', models.CharField(default=None, max_length=100)),
                ('address', models.CharField(default=None, max_length=100)),
                ('description', models.CharField(default=None, max_length=100)),
                ('status', models.IntegerField()),
                ('orphanage_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='homepage.Orphanage')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'get_latest_by': ['tid', 'status'],
            },
        ),
        migrations.CreateModel(
            name='donatemoney',
            fields=[
                ('tid', models.AutoField(primary_key=True, serialize=False)),
                ('transfer', models.CharField(default=0, max_length=264)),
                ('amount', models.IntegerField(default=0)),
                ('orphanage_name', models.CharField(default=None, max_length=100)),
                ('status', models.IntegerField()),
                ('date_of_donation', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.CharField(default=None, max_length=50)),
                ('orphanage_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='homepage.Orphanage')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'get_latest_by': ['tid', 'status'],
            },
        ),
        migrations.CreateModel(
            name='AddOrphan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('find_place', models.CharField(max_length=100)),
                ('ref_no', models.IntegerField()),
                ('date_of_birth', models.DateField()),
                ('orphanage_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='homepage.Orphanage')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
