# Generated by Django 2.2.5 on 2019-12-11 16:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0009_auto_20191211_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='canbereviewed',
            field=models.CharField(default='No', max_length=30),
        ),
        migrations.AlterField(
            model_name='verification',
            name='hit',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 11, 21, 32, 23, 957729)),
        ),
    ]
