# Generated by Django 2.2.6 on 2019-12-12 06:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0014_auto_20191212_0344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donatemoney',
            name='description',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='verification',
            name='hit',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 12, 12, 20, 24, 751958)),
        ),
    ]
